version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dishdollar
    ports:
      - "5050:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
